# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Tempo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Tempo
  pod 'Alamofire'
  pod 'SwiftProtobuf', git: 'https://github.com/apple/swift-protobuf.git', :tag => '1.0.2'

end
